# Fichier de configuration pour Render
services:
  - type: web
    name: quran-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TRANSFORMERS_CACHE
<<<<<<< HEAD
        value: /tmp/cache
=======
        value: /tmp/cache
>>>>>>> 23f01e7f82e252c6c06cf25fad0065f2fdb8273e
